### ISSUE TITLE
can we use llvm/clang to build musl libc

### ISSUE THREAD

**Issue by unicornx** [richfelker/musl-cross-make#109]
As question in title, can we use llvm/clang to build musl c lib? Or any guide I can follow to build it? Thanks in adv.

**Comment by richfelker** [comment]
Yes, but it's not related to musl-cross-make, which is specifically a build system for a GCC based toolchain. Building musl itself with clang is easy - just pass `CC=clang` or similar to musl's configure script. Getting a setup to invoke clang for musl targets without starting with a musl-based system is probably what you actually want to do, but the procedure and even the concepts involved (since LLVM/clang is always a universal cross compiler) are very different and outside the scope of mcm. You're welcome to ask on the mailing list or IRC (Freenode #musl) about it though. This is definitely an area where I'd like to have better guides/documentation, but I'm not particularly familiar with the process.

**Comment by unicornx** [comment]
> Yes, but it's not related to musl-cross-make, which is specifically a build system for a GCC based toolchain. Building musl itself with clang is easy - just pass `CC=clang` or similar to musl's configure script. Getting a setup to invoke clang for musl targets without starting with a musl-based system is probably what you actually want to do, but the procedure and even the concepts involved (since LLVM/clang is always a universal cross compiler) are very different and outside the scope of mcm. You're welcome to ask on the mailing list or IRC (Freenode #musl) about it though. This is definitely an area where I'd like to have better guides/documentation, but I'm not particularly familiar with the process.

Thank you Rich, I just joined the musl maillist :)
