### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by ollieparanoid** [richfelker/musl-cross-make#25]
Please add a LICENSE file, so this can be packaged properly.

Thank you!

**Comment by slackhead** [comment]
Please!

**Comment by richfelker** [comment]
Can you clarify what you're trying to package? If you are packaging the *output* of mcm (a binary toolchain), the relevant licenses are those for GCC, binutils, and musl. Using a license file for mcm itself (the build script) in such a package would be wrong since no derivative work of mcm is included in the output, and since mcm's license couldn't override those of the programs it's building.

If you actually want to package mcm itself as a tool for letting the user build cross toolchains, that perhaps requires some action to document the license.

**Comment by slackhead** [comment]
In my case, the second, although it will take some work for me to get a script together yet.

**Comment by slackhead** [comment]
Actually, I've done a simple cross compiler script that will take target and host options.  I'm tryng to get a cross native script working, and then maybe use custom package names depending on the target etc,

**Comment by richfelker** [comment]
Fixed by merging #80.
