### ISSUE TITLE
strip symbols

### ISSUE THREAD

**Issue by BlueMax** [richfelker/musl-cross-make#38]
Hallo,
how can i create a toolchain with stripped symbols (eg. libc.so)? I though LDFLAGS="-s" in config.mak would do that but it doesn't. My libc.so is 750kb and after (manual) stripping its 500kb.

What's the difference between COMMON_CONFIG and GCC_CONFIG? The litecross/MAKEFILE just adds them in a row. 

Edit: With 'stripped' i mean to have -g0 (no debug infos) and such honored as well. In the end i want an optimized -O2 release without any debug/symbol information (especially for *.a files).

config.mak:
```
TARGET = arm-linux-musleabihf
COMMON_CONFIG += CFLAGS="-g0 -O2" CXXFLAGS="-g0 -O2" LDFLAGS="-s"
GCC_CONFIG += --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-tune=cortex-a9 --with-mode=thumb
GCC_CONFIG += --enable-threads=posix --disable-nls
GCC_CONFIG += --disable-multilib

GCC_VER = 7.2.0
LINUX_VER = 
```

**Comment by richfelker** [comment]
In order to pass options to musl, you need something like:

`MUSL_CONFIG += LDFLAGS="-s"`

By default musl itself is built without debug symbols, so it seems that the ones you're getting are coming in from libgcc or something. It might make sense for musl to auto-add `-s` to `LDFLAGS` if `-g` isn't in use, but if so that should be discussed on musl list.

The difference between `COMMON_CONFIG` and `GCC_CONFIG` is not currently visible. It comes from when GCC and binutils were built in separate trees - `COMMON_CONFIG` was passed to both GCC and binutils configure. We're going to go back to using 2 build trees at some point due to problems with the current method, and when we do, they'll retain the old meanings.

**Comment by BlueMax** [comment]
Works properly indeed. Thanks!
