### ISSUE TITLE
Mingw (HOST = 86_64-w64-mingw32)

### ISSUE THREAD

**Issue by Spirit3s** [richfelker/musl-cross-make#55]
Hi,

this is not really a issue, is more a question.

I've been using musl-cross-make to build a toolchain for a t1042(ppc64) dev board.

In linux everything is ok.

For Windows i'm trying to build using mingw, even in linux for canadian cross compilation(using "--host=").

But i couldnt put it to work.

Have anyone been able to build a cross compiler musl for mingw? 

Best Regards.

**Comment by richfelker** [comment]
Yes, I've even been able to cross-compile it (canadian cross) since I don't have any way to natively build on Windows.

For this to work you need an existing gcc toolchain targeting Windows/mingw. Then:

`make TARGET=x86_64-linux-musl HOST=x86_64-w64-mingw32`

Substitute whichever musl target you like.

I suspect it's a lot less likely to work building natively on Windows due to lack of working symlinks and similar issues. Using cygwin or in the future midipix (or WSL with a Linux-to-mingw cross toolchain) is probably going to be needed there.

**Comment by Spirit3s** [comment]
thank you for the answer.

the problem is , when i set the HOST = , the Makefile will start from the musl configuration
for some reason , and then it cant find the compiler because it jumped that part.

vagrant@vagrant:~/musl-cross-make$ make TARGET=x86_64-linux-musl HOST=x86_64-w64-mingw32
cd build/x86_64-w64-mingw32/x86_64-linux-musl && make all
make[1]: Entering directory '/home/vagrant/musl-cross-make/build/x86_64-w64-mingw32/x86_64-linux-musl'
cd obj_musl && ../src_musl/configure  --prefix= --host=x86_64-linux-musl
checking for C compiler...
../src_musl/configure: cannot find a C compiler
Makefile:234: recipe for target 'obj_musl/.lc_configured' failed
make[1]: *** [obj_musl/.lc_configured] Error 1
make[1]: Leaving directory '/home/vagrant/musl-cross-make/build/x86_64-w64-mingw32/x86_64-linux-musl'
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by richfelker** [comment]
Yes, I neglected to mention that you need to already have a suitable cross compiler that runs on the system you're building on and targets the same target, in order to build both musl and the gcc target libs. Currently this needs to be installed in your PATH prior to running mcm's make; in the future I might add a framework for building and using it in-tree.

**Comment by Spirit3s** [comment]
Thank for your help, worked like a charm

**Comment by Spirit3s** [comment]
> you need to already have a suitable cross compiler that runs on the system you're building on and targets the same target, in order to build both musl and the gcc target libs.

My idea was to generate a compiler in linux , with powerpc64 as target , and windows as host. And it work's, but you need to build it first for linux and then for ming32

**Comment by Spirit3s** [comment]
>
