### ISSUE TITLE
Producing a fully static toolchain

### ISSUE THREAD

**Issue by CaseyBakey** [richfelker/musl-cross-make#64]
Hello there,

Before all, thanks a lot for this useful project! I've successfully built and used toolchains produced by this project.

But I encountered a problem when a toolchain built on Ubuntu 16.04 (for example), is used on Ubuntu 18.04. The gcc from the toolchain is then complaining about a missing glibc 2.21 (it's 2.27 on 18.04).

That's when I realised that the produced toolchains are dynamically linked (or at least gcc and the different binutils). And I found that's a pitty since they're already portable/relocatable.

So my question is: is it possible, by giving the good combinations of COMMON_CONFIG/BINUTILS_CONFIG/GCC_CONFIG to litecross, to produce fully static toolchains that could be used on any Linux distros ?

I've already messed with, but maybe in the wrong variables: 

 --static
 -all-static
 --disable-shared
 -static-libstdc++
 -static-libgcc

Thanks a lot for your answer!

**Comment by mathieu-aubin** [comment]
try setting some CFLAGS values while configuring

i use the following sometimes (taken from a 'compile', script i created)

`
CC="/opt/musl/1.1.21/bin/musl-gcc" CFLAGS="-Os -s -pipe -static -static-libgcc -static-libstdc++ -fomit-frame-pointer -fPIC -Wl,-z,relro,-z,now" ./configure
`

you should check the dependencies for the project you are trying to compile but for example, a straight C file can be compiled statically using something similar to

`musl-gcc -static -static-libgcc -static-libstdc++ -fPIC file.c -o output_static_file `

would work with gcc too but adds tons of libc 'garbage' (if i can say so)

**Comment by richfelker** [comment]
There's an example in `config.mak.dist` for static linking. You need both `-static` and `--static` (to work around malicious libtool behavior of reinterpreting `-static` to mean "just link the libs build as part of this package statically but still dynamic link to system libs") in both `CC` and `CXX` (because gcc and binutils have C++ sources too).

**Comment by ryanwoodsmall** [comment]
I ended up doing two rounds of compiling, once to build a musl toolchain, then, using thenew toolchain, building a final static toolchain. Guess this is sort of like a native cross-compile. I'm still not totally sure of flags here, but it works well enough; I do still see PIC problems with the libstdc++ demangler when attempting to link a fully-compiled static libstdc++.a with a shared library. C works just fine. 

first toolchain config.mak:
```
BINUTILS_CONFIG += --disable-lto
COMMON_CONFIG += CFLAGS="-fPIC -g0 -Os" CXXFLAGS="-fPIC -g0 -Os"
COMMON_CONFIG += --disable-nls
COMMON_CONFIG += LDFLAGS=" -s"
DL_CMD = curl -k -C - -L -o
GCC_CONFIG += --disable-lto
GCC_CONFIG += --disable-multilib
GCC_CONFIG += --enable-languages=c,c++
OUTPUT = /tmp/blah/shared-build
TARGET = x86_64-linux-musl
```

final toolchain config.mak:
```
BINUTILS_CONFIG += --disable-lto
COMMON_CONFIG += CC="x86_64-linux-musl-gcc -static --static" CXX="x86_64-linux-musl-g++ -static --static"
COMMON_CONFIG += CFLAGS="-fPIC -g0 -Os" CXXFLAGS="-fPIC -g0 -Os"
COMMON_CONFIG += --disable-nls
COMMON_CONFIG += --enable-shared=no --disable-shared --enable-static=yes --enable-static
COMMON_CONFIG += LDFLAGS=" -s --static"
DL_CMD = curl -k -C - -L -o
GCC_CONFIG += --disable-host-shared
GCC_CONFIG += --disable-lto
GCC_CONFIG += --disable-multilib
GCC_CONFIG += --enable-languages=c,c++
OUTPUT = /tmp/blah/static-build
TARGET = x86_64-linux-musl
```

This results in exactly one shared lib: libc.so; using "-static" when linking links against libc.a as expected, so it's as close to fully static as I could manage.

I ended up needing this repeatable on Alpine, CentOS and Ubuntu for a project, Alpine worked correctly every time. The others did not, outputting "sorta-static but not really" to "no .a files anywhere, everything is still .so despite being told otherwise." I threw a Makefile together that generates static compilers I ended up using to build musl-based static stuff on Chrome/Chromium OS:

https://github.com/ryanwoodsmall/musl-misc/blob/master/musl-cross-make-confs/Makefile.arch_indep

Built and used on aarch64/arm/i386/x86_64 - but beware: this patches in a custom ld.so location.

slibtool is a pretty great replacement for libtool as well, and does the right thing with static linking when libtool ignores/second-guesses: https://github.com/midipix-project/slibtool

**Comment by CaseyBakey** [comment]
Sorry I didn't take take time to close this issue, but it got resolved by @richfelker comment.

I got fully static toolchains now.

**Comment by Kreijstal** [comment]
> Sorry I didn't take take time to close this issue, but it got resolved by [@richfelker](https://github.com/richfelker) comment.
> 
> I got fully static toolchains now.

can we download them?

**Comment by CaseyBakey** [comment]
If you build them and upload them somewhere first, yes ;)
